outDir: "out"

extract:
  title: .post-title h3>a[href]
  links: .col-md-12.post-block>div:nth-child(3)>div:nth-child(7)
  description: .the-content-container

pages:
  - https://godownloads.net/triune-digital-electric-pack-download/
  # - https://godownloads.net/30-grunge-cardboard-photoshop-brushes-free-download/
  # - https://godownloads.net/nude-neutral-modern-procreate-color-ipad-free-download/
  # - https://godownloads.net/forest-tales-procreate-brushes-free-download/
  # - https://godownloads.net/natural-procreate-brushes-free-download/
  # - https://godownloads.net/150-dinosaur-procreate-stamps-set-free-download/
  # - https://godownloads.net/creativemarket-national-park-stamp-6665068-free-download/
  # - https://godownloads.net/flowers-and-leaves-photoshop-brushes-free-download/
  # - https://godownloads.net/videohive-claps-dynamic-urban-opener-36946736-free-download/
  # - https://godownloads.net/videohive-liquid-stickers-for-davinci-resolve-36976042-free-download/
  # - https://godownloads.net/videohive-razor-glitch-titles-36929303-free-download/
  # - https://godownloads.net/videohive-social-mediatik-tokdav-36948751-free-downloaad/
  # - https://godownloads.net/videohive-colorful-shape-transitions-davinci-resolve-36949913-free-download/
  # - https://godownloads.net/videohive-war-opener-dr-36915496-free-download/
  # - https://godownloads.net/videohive-film-credits-titles-36892105-free-download/
  # - https://godownloads.net/videohive-neon-lights-titles-davinci-resolve-36890302-free-download/
  # - https://godownloads.net/videohive-meditation-yoga-logo-reveal-36889797-free-download/
  # - https://godownloads.net/videohive-running-sport-logo-reveal-36889752-free-download/
  # - https://godownloads.net/videohive-mosaic-cubics-logo-reveal-for-davinci-resolve-36876891-free-download/
  # - https://godownloads.net/videohive-cartoon-titles-pack-davinci-resolve-36868036-free-download/
  # - https://godownloads.net/videohive-abstract-elements-for-davinci-resolve-36866781-free-download/
  # - https://godownloads.net/videohive-triangle-opener-davinci-resolve-36532358-free-download/
  # - https://godownloads.net/videohive-hand-drawn-elements-36495505-free-download/
  # - https://godownloads.net/videohive-fast-glitch-gaming-log-36495478-free-download/
  # - https://godownloads.net/videohive-dynamic-trap-opener-36493899-free-download/
  # - https://godownloads.net/videohive-stomp-dynamic-fast-opener-36492623-free-download/
  # - https://godownloads.net/videohive-3d-abstract-object-logo-opener-36482074-free-download/
  # - https://godownloads.net/videohive-multimedia-and-gaming-icons-36478063-free-download/
  # - https://godownloads.net/videohive-shape-elements-pack-davinci-resolve-36475606-free-download/
  # - https://godownloads.net/videohive-youtube-subscribe-buttons-davinci-resolve-36474559-free-download/
  # - https://godownloads.net/videohive-sweets-pack-davinci-resolve-36475562-free-download/
  # - https://godownloads.net/videohive-sparks-pack-davinci-resolve-36473508-free-download/
  # - https://godownloads.net/videohive-ramadan-openers-davinci-resolve-36474047-free-download/
